FROM maven:3-eclipse-temurin-25 AS build
WORKDIR /opt/app
COPY src ./src
COPY pom.xml .
RUN --mount=type=cache,target=~/.m2 mvn -f /opt/app/pom.xml package -DskipTests

FROM bellsoft/liberica-openjre-debian:25

RUN mkdir -p /opt/app

COPY --from=build /opt/app/target/taskmanager-0.0.6-SPRING-SNAPSHOT.jar /opt/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/opt/app.jar"]