FROM maven:3-eclipse-temurin-25 AS build
WORKDIR /build
COPY src ./src
COPY pom.xml .
RUN --mount=type=cache,target=~/.m2 mvn -f /build/pom.xml package -DskipTests

FROM eclipse-temurin:25-alpine AS jre-build
WORKDIR /jrebuild
COPY --from=build /build/target/taskmanager-0.0.6-SPRING-SNAPSHOT.jar .
RUN jar xf taskmanager-0.0.6-SPRING-SNAPSHOT.jar
RUN jdeps --ignore-missing-deps -q \
    --recursive \
    --multi-release 25 \
    --print-module-deps \
    --class-path 'BOOT-INF/lib/*' \
    taskmanager-0.0.6-SPRING-SNAPSHOT.jar > deps.info
RUN jlink \
    --verbose \
    --add-modules $(cat deps.info) \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /customjre

FROM bellsoft/liberica-openjre-debian:25 AS extractor
WORKDIR /extract
COPY --from=build /build/target/taskmanager-0.0.6-SPRING-SNAPSHOT.jar application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination extracted

FROM alpine:3.18
# Create appuser
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /application
# Copy custom JRE
COPY --from=jre-build /customjre /opt/jre
ENV JAVA_HOME=/opt/jre
ENV PATH="$PATH:$JAVA_HOME/bin"
# Copy layered jar contents
COPY --from=extractor /extract/extracted/dependencies/ ./
COPY --from=extractor /extract/extracted/spring-boot-loader/ ./
COPY --from=extractor /extract/extracted/snapshot-dependencies/ ./
COPY --from=extractor /extract/extracted/application/ ./
# Set permissions
RUN chown -R appuser:appgroup /application
USER appuser
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "application.jar"]
