FROM maven:3-eclipse-temurin-25 AS maven-build
WORKDIR /opt/app
COPY src ./src
COPY pom.xml .
RUN --mount=type=cache,target=~/.m2 mvn -f /opt/app/pom.xml package -DskipTests


FROM eclipse-temurin:25-alpine AS jre-build
WORKDIR /opt/app
COPY --from=maven-build /opt/app/target/taskmanager-0.0.6-SPRING-SNAPSHOT.jar .
RUN jar xf taskmanager-0.0.6-SPRING-SNAPSHOT.jar
RUN jdeps --ignore-missing-deps -q  \
    --recursive  \
    --multi-release 25  \
    --print-module-deps  \
    --class-path 'BOOT-INF/lib/*'  \
    taskmanager-0.0.6-SPRING-SNAPSHOT.jar > deps.info
RUN jlink \
    --verbose \
    --add-modules $(cat deps.info) \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /customjre



FROM alpine:3.18
COPY --from=jre-build /customjre /opt/jre
ENV JAVA_HOME=/opt/jre
ENV PATH="$PATH:$JAVA_HOME/bin"

COPY --from=maven-build /opt/app/target/taskmanager-0.0.6-SPRING-SNAPSHOT.jar /opt/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/opt/app.jar"]